'use strict';
// 📜 Starobylé zvitky (obťažnosť „prastará“): história objavov — roky, autori, ich rozhovory a slávne výroky.
// Zvitok sa ukáže pred krokom levelu `step` (názov metódy kroku; 'finale' = pred záverečnou skúškou)
// a zostane v Kódexe na karte „📜 Zvitky“. Citáty sú v preklade; pri anekdotách je to uvedené.

const SCROLLS = [
  // ---------- 1 · Komplexný prístav ----------
  { id: 's1a', level: 1, step: 'intro', year: '1545 – 1572', people: 'Gerolamo Cardano, Rafael Bombelli',
    title: ['Odmocnina zo záporného čísla', 'The square root of a negative number'],
    text: ['Cardano v knihe <i>Ars Magna</i> (1545) pri riešení úlohy „rozdeľ 10 na dve časti so súčinom 40“ dostal 5 ± √−15. Výsledok vyhovoval, no nevedel, čo znamená. Bombelli v <i>L’Algebra</i> (1572) ako prvý zaviedol pravidlá počítania s „più di meno“ (dnešné +i) a „meno di meno“ (−i) — a ukázal, že cez ne vedú cesty k úplne reálnym koreňom kubických rovníc.',
      'In <i>Ars Magna</i> (1545), solving “divide 10 into two parts whose product is 40”, Cardano obtained 5 ± √−15. The result worked, but he did not know what it meant. Bombelli, in <i>L’Algebra</i> (1572), was the first to give rules for calculating with “più di meno” (today’s +i) and “meno di meno” (−i) — and showed that they lead to perfectly real roots of cubic equations.'],
    quote: ['„Tak postupuje aritmetická jemnosť, ktorej koniec je, ako sa hovorí, rovnako rafinovaný ako zbytočný.“ — Cardano o √−15', '“So progresses arithmetic subtlety, the end of which, as is said, is as refined as it is useless.” — Cardano on √−15'] },
  { id: 's1b', level: 1, step: 'timesI', year: '1637 · 1748 · 1777', people: 'René Descartes, Leonhard Euler',
    title: ['„Imaginárne“ a Eulerov vzorec', '“Imaginary” and Euler’s formula'],
    text: ['Descartes v <i>La Géométrie</i> (1637) nazval tieto korene pohŕdavo „imaginárne“ — a meno zostalo. Euler v <i>Introductio in analysin infinitorum</i> (1748) publikoval e<sup>ix</sup> = cos x + i sin x a v roku 1777 zaviedol pre √−1 písmeno <b>i</b>. Už v liste Goldbachovi (1746) vypočítal, že i<sup>i</sup> je reálne číslo ≈ 0,2079.',
      'In <i>La Géométrie</i> (1637) Descartes called these roots, dismissively, “imaginary” — and the name stuck. In <i>Introductio in analysin infinitorum</i> (1748) Euler published e<sup>ix</sup> = cos x + i sin x, and in 1777 he introduced the letter <b>i</b> for √−1. Already in a letter to Goldbach (1746) he had computed that i<sup>i</sup> is a real number ≈ 0.2079.'],
    quote: ['„Náš klenot … najpozoruhodnejší vzorec v matematike.“ — Richard Feynman o e<sup>iθ</sup> = cos θ + i sin θ (Feynmanove prednášky, 1963)', '“Our jewel … the most remarkable formula in mathematics.” — Richard Feynman on e<sup>iθ</sup> = cos θ + i sin θ (The Feynman Lectures, 1963)'] },
  { id: 's1c', level: 1, step: 'interference', year: '1799 · 1806 · 1926', people: 'Caspar Wessel, Jean-Robert Argand, Max Born',
    title: ['Čísla ako šípky a pravdepodobnosť ako štvorec', 'Numbers as arrows, probability as a square'],
    text: ['Zememerač Wessel (1799) a účtovník Argand (1806) nezávisle nakreslili komplexné čísla ako body roviny — násobenie sa stalo otáčaním. Gauss (1831) im dal meno „komplexné“. V roku 1926 Max Born v poznámke pod čiarou článku o zrážkach doplnil, že pravdepodobnosť je úmerná <b>štvorcu</b> amplitúdy — dnešné Bornovo pravidlo (Nobelova cena 1954).',
      'The surveyor Wessel (1799) and the bookkeeper Argand (1806) independently drew complex numbers as points of a plane — multiplication became rotation. Gauss (1831) gave them the name “complex”. In 1926 Max Born added in a footnote of a paper on collisions that the probability is proportional to the <b>square</b> of the amplitude — today’s Born rule (Nobel Prize 1954).'],
    quote: ['„Pohyb častíc sa riadi zákonmi pravdepodobnosti, ale samotná pravdepodobnosť sa šíri v súlade so zákonom kauzality.“ — Max Born, 1926', '“The motion of particles follows probability laws but the probability itself propagates according to the law of causality.” — Max Born, 1926'] },

  // ---------- 2 · Sternova–Gerlachova pec ----------
  { id: 's2a', level: 2, step: 'intro', year: '1921 – 1922', people: 'Otto Stern, Walther Gerlach, Niels Bohr',
    title: ['Pohľadnica Bohrovi', 'A postcard to Bohr'],
    text: ['Stern navrhol pokus v roku 1921, aby vyvrátil Bohrovu „priestorovú kvantizáciu“. Po mesiacoch neúspechov Gerlach vo Frankfurte vo februári 1922 uvidel na sklíčku stopu rozdelenú na dve. Poslal Bohrovi pohľadnicu s mikrofotografiou dvoch stôp. (Až neskôr sa ukázalo, že nejde o orbitálny moment, ale o spin elektrónu.)',
      'Stern proposed the experiment in 1921, aiming to disprove Bohr’s “space quantisation”. After months of failure, Gerlach in Frankfurt saw, in February 1922, the deposit on the glass plate split in two. He sent Bohr a postcard with a micrograph of the two spots. (Only later did it turn out that the effect was not orbital angular momentum but electron spin.)'],
    quote: ['„V prílohe experimentálny dôkaz smerovej kvantizácie. Blahoželáme k potvrdeniu vašej teórie.“ — Gerlach Bohrovi, 8. 2. 1922', '“Attached is the experimental proof of directional quantisation. We congratulate you on the confirmation of your theory.” — Gerlach to Bohr, 8 Feb 1922'] },
  { id: 's2b', level: 2, step: 'twoSpots', year: '1922', people: 'Otto Stern',
    title: ['Lacná cigara', 'A cheap cigar'],
    text: ['Vrstva striebra na sklíčku bola taká tenká, že ju nebolo vidno. Podľa Sternových spomienok sa stopa zjavila až vtedy, keď sa nad sklíčko naklonil s lacnou cigarou: síra z dymu premenila striebro na čierny sulfid striebra. Fyzici Friedrich a Herschbach pokus s cigarou v roku 2003 zopakovali — funguje (anekdota, ale overená).',
      'The silver layer on the plate was so thin that it could not be seen. According to Stern’s recollection, the trace appeared only when he leaned over the plate with a cheap cigar: sulphur from the smoke turned the silver into black silver sulphide. The physicists Friedrich and Herschbach repeated the cigar trick in 2003 — it works (an anecdote, but a tested one).'],
    quote: ['Stern s platom asistenta fajčil lacné cigary s vysokým obsahom síry — a práve to pokus zachránilo. — podľa Friedricha a Herschbacha, Physics Today (2003)', 'On an assistant’s salary Stern smoked cheap cigars with a high sulphur content — and that is what saved the experiment. — after Friedrich and Herschbach, Physics Today (2003)'] },
  { id: 's2c', level: 2, step: 'sequences', year: '1925 · 1927', people: 'George Uhlenbeck, Samuel Goudsmit, Paul Ehrenfest, Wolfgang Pauli',
    title: ['Spin: hlúposť, ktorú si mladí môžu dovoliť', 'Spin: a foolishness the young can afford'],
    text: ['V roku 1925 Uhlenbeck a Goudsmit navrhli, že elektrón má vlastný moment hybnosti ±ħ/2. Keď im Lorentz vypočítal, že „povrch“ elektrónu by sa točil rýchlejšie ako svetlo, chceli článok stiahnuť — Ehrenfest ho už odoslal. Pauli bol najprv proti (Kronigovi ten istý nápad rozhovoril). Phipps a Taylor (1927) zopakovali Stern–Gerlachov pokus s atómami vodíka a potvrdili, že dve stopy robí spin elektrónu.',
      'In 1925 Uhlenbeck and Goudsmit proposed that the electron has an intrinsic angular momentum ±ħ/2. When Lorentz calculated that the electron’s “surface” would spin faster than light, they wanted to withdraw the paper — Ehrenfest had already sent it. Pauli was against it at first (he had talked Kronig out of the same idea). Phipps and Taylor (1927) repeated the Stern–Gerlach experiment with hydrogen atoms and confirmed that the two spots come from electron spin.'],
    quote: ['„Obaja ste dosť mladí na to, aby ste si mohli dovoliť nejakú hlúposť.“ — Ehrenfest Uhlenbeckovi a Goudsmitovi, 1925', '“You are both young enough to be able to afford a stupidity.” — Ehrenfest to Uhlenbeck and Goudsmit, 1925'] },

  // ---------- 3 · Blochovo observatórium ----------
  { id: 's3a', level: 3, step: 'intro', year: '1892 · 1927', people: 'Henri Poincaré, Wolfgang Pauli',
    title: ['Guľa skôr než qubit', 'A sphere before the qubit'],
    text: ['Tú istú guľu poznala optika: Poincaré (1892) zobrazil všetky polarizácie svetla ako body sféry — kruhová polarizácia na póloch, lineárne na rovníku. Pauli v roku 1927 zapísal spin pomocou troch matíc σ<sub>x</sub>, σ<sub>y</sub>, σ<sub>z</sub>; ich lineárne kombinácie sú presne rotácie Blochovej sféry.',
      'Optics knew the same sphere: Poincaré (1892) mapped every polarisation of light to a point of a sphere — circular polarisation at the poles, linear on the equator. In 1927 Pauli wrote spin using three matrices σ<sub>x</sub>, σ<sub>y</sub>, σ<sub>z</sub>; their linear combinations are exactly the rotations of the Bloch sphere.'],
    quote: ['„Matematika je umenie dávať rovnaké meno rôznym veciam.“ — Henri Poincaré', '“Mathematics is the art of giving the same name to different things.” — Henri Poincaré'] },
  { id: 's3b', level: 3, step: 'puzzles', year: '1946 · 1952 · 1957', people: 'Felix Bloch, Edward Purcell, Feynman, Vernon, Hellwarth',
    title: ['Jadrová indukcia a geometrický obraz', 'Nuclear induction and a geometric picture'],
    text: ['V roku 1946 Bloch (Stanford) a Purcell (Harvard) nezávisle objavili jadrovú magnetickú rezonanciu v látkach; Nobelovu cenu si rozdelili v roku 1952. Bloch zapísal pohyb magnetizácie ako rotáciu vektora. Feynman, Vernon a Hellwarth (1957) ukázali, že <i>každý</i> dvojhladinový systém sa dá kresliť ako šípka v guli — preto dnes hovoríme o Blochovej sfére qubitu.',
      'In 1946 Bloch (Stanford) and Purcell (Harvard) independently discovered nuclear magnetic resonance in matter; they shared the Nobel Prize in 1952. Bloch described the motion of magnetisation as the rotation of a vector. Feynman, Vernon and Hellwarth (1957) showed that <i>any</i> two-level system can be drawn as an arrow in a ball — which is why we speak of the Bloch sphere of a qubit today.'],
    quote: ['Heisenberg: „Priestor je pole lineárnych operácií.“ Bloch: „Nezmysel. Priestor je modrý a lietajú ním vtáky.“ — Blochova spomienka na rozhovor s Heisenbergom (Physics Today, 1976)', 'Heisenberg: “Space is the field of linear operations.” Bloch: “Nonsense. Space is blue and birds fly through it.” — Bloch recalling a conversation with Heisenberg (Physics Today, 1976)'] },
  { id: 's3c', level: 3, step: 'lab', year: '1995', people: 'Benjamin Schumacher',
    title: ['Slovo „qubit“', 'The word “qubit”'],
    text: ['Slovo <b>qubit</b> zaviedol Benjamin Schumacher v článku <i>Quantum coding</i> (1995) — vraj ako žart z rozhovoru s Williamom Woottersom (znie ako biblická jednotka „cubit“, lakeť). V tom istom článku ukázal, že qubit je jednotka kvantovej informácie, tak ako bit je jednotkou klasickej.',
      'The word <b>qubit</b> was introduced by Benjamin Schumacher in the paper <i>Quantum coding</i> (1995) — reportedly as a joke from a conversation with William Wootters (it sounds like the biblical unit “cubit”). In the same paper he showed that the qubit is the unit of quantum information, just as the bit is the unit of classical information.'],
    quote: ['„Termín ‚qubit‘ vznikol zo žartu počas jedného z mnohých podnetných rozhovorov autora s W. K. Woottersom.“ — Schumacher, Quantum coding (1995)', '“The term ‘qubit’ was coined in jest during one of the author’s many intriguing and valuable conversations with W. K. Wootters.” — Schumacher, Quantum coding (1995)'] },

  // ---------- 4 · Chrám interferencie ----------
  { id: 's4a', level: 4, step: 'intro', year: '1801 – 1803 · 1909', people: 'Thomas Young, Geoffrey Ingram Taylor',
    title: ['Dve štrbiny a slabé svetlo', 'Two slits and feeble light'],
    text: ['Young (prednášky 1801–1803 v Kráľovskej spoločnosti) ukázal prúžky za dvoma štrbinami a tým vlnovú povahu svetla — proti autorite Newtona. Taylor (1909) zopakoval interferenciu so svetlom také slabým, že naraz letel v prístroji v priemere menej než jeden fotón; expozícia trvala tri mesiace a prúžky zostali.',
      'Young (lectures 1801–1803 at the Royal Society) showed fringes behind two slits and thus the wave nature of light — against Newton’s authority. Taylor (1909) repeated the interference with light so feeble that on average less than one photon was inside the apparatus at a time; the exposure took three months and the fringes remained.'],
    quote: ['„Pokusy, ktoré idem opísať, sa dajú zopakovať s veľkou ľahkosťou, kedykoľvek svieti slnko.“ — Thomas Young, 1803', '“The experiments I am about to relate … may be repeated with great ease, whenever the sun shines.” — Thomas Young, 1803'] },
  { id: 's4b', level: 4, step: 'withMeasure', year: '1961 · 1974 · 1989', people: 'Claus Jönsson; Merli, Missiroli, Pozzi; Akira Tonomura',
    title: ['Elektróny po jednom', 'Electrons one at a time'],
    text: ['Jönsson (1961) prvý urobil dvojštrbinový pokus s elektrónmi. Merli, Missiroli a Pozzi (Bologna, 1974) a Tonomura (Hitachi, 1989) poslali elektróny <i>po jednom</i>: každý dopadne ako bodka, no tisíce bodiek poskladajú prúžky. Čitatelia Physics World ho v roku 2002 zvolili za najkrajší pokus vo fyzike.',
      'Jönsson (1961) was first to perform the double-slit experiment with electrons. Merli, Missiroli and Pozzi (Bologna, 1974) and Tonomura (Hitachi, 1989) sent electrons <i>one at a time</i>: each lands as a dot, yet thousands of dots build up fringes. In 2002 the readers of Physics World voted it the most beautiful experiment in physics.'],
    quote: ['„Je to jav, ktorý je nemožné, absolútne nemožné vysvetliť klasicky, a obsahuje v sebe srdce kvantovej mechaniky. V skutočnosti obsahuje jediné tajomstvo.“ — Feynman, 1965', '“A phenomenon which is impossible, absolutely impossible, to explain in any classical way, and which has in it the heart of quantum mechanics. In reality, it contains the only mystery.” — Feynman, 1965'] },
  { id: 's4c', level: 4, step: 'deco', year: '1927 · 1970 · 1981', people: 'John von Neumann, Lev Landau, H. Dieter Zeh, Wojciech Zurek',
    title: ['Matica hustoty a dekoherencia', 'The density matrix and decoherence'],
    text: ['Maticu hustoty zaviedli nezávisle von Neumann a Landau (1927) na opis zmesí a podsystémov. Zeh (1970) si všimol, že makroskopické systémy sa nedajú izolovať od okolia, a Zurek (1981–82) ukázal, ako prostredie vyberá „ukazovateľovú“ bázu a maže koherencie. V laboratóriu dekoherenciu „v priamom prenose“ zmerali Haroche a kolegovia (1996).',
      'The density matrix was introduced independently by von Neumann and Landau (1927) to describe mixtures and subsystems. Zeh (1970) noticed that macroscopic systems cannot be isolated from their environment, and Zurek (1981–82) showed how the environment selects a “pointer” basis and wipes out coherences. Haroche and colleagues measured decoherence “live” in the lab (1996).'],
    quote: ['„Kvantová teória je jediná, ktorú máme; dekoherencia ukazuje, prečo sa nám svet javí klasický.“ — parafráza myšlienky W. Zureka', '“Quantum theory is the only one we have; decoherence shows why the world looks classical to us.” — a paraphrase of W. Zurek’s idea'] },

  // ---------- 5 · Diracova knižnica ----------
  { id: 's5a', level: 5, step: 'intro', year: '1925 – 1930', people: 'Paul Dirac, Werner Heisenberg',
    title: ['Poissonova zátvorka na prechádzke', 'A Poisson bracket on a walk'],
    text: ['V lete 1925 dostal 23-ročný Dirac korektúry Heisenbergovho článku. Na nedeľnej prechádzke si uvedomil, že komutátor xp − px zodpovedá klasickej Poissonovej zátvorke — v nedeľu však bola knižnica zatvorená, a tak musel do pondelka čakať, kým si vzorec overí. V roku 1930 vydal <i>The Principles of Quantum Mechanics</i>; bra-ket zápis pridal v roku 1939.',
      'In the summer of 1925 the 23-year-old Dirac received the proofs of Heisenberg’s paper. On a Sunday walk he realised that the commutator xp − px corresponds to the classical Poisson bracket — but the library was closed on Sunday, so he had to wait until Monday to check the formula. In 1930 he published <i>The Principles of Quantum Mechanics</i>; he added the bra-ket notation in 1939.'],
    quote: ['„Je dôležitejšie mať krásu v rovniciach, než aby súhlasili s experimentom.“ — Dirac, Scientific American, 1963', '“It is more important to have beauty in one’s equations than to have them fit experiment.” — Dirac, Scientific American, 1963'] },
  { id: 's5b', level: 5, step: 'tasks', year: '1928 · 1932 · 1933', people: 'Paul Dirac, Carl Anderson, Erwin Schrödinger',
    title: ['Rovnica, ktorá predpovedala antihmotu', 'The equation that predicted antimatter'],
    text: ['Diracova relativistická rovnica (1928) mala riešenia so zápornou energiou. Dirac v nich nakoniec (1931) videl novú časticu — anti-elektrón. Anderson ho v roku 1932 našiel v kozmickom žiarení (pozitrón). Dirac dostal Nobelovu cenu v roku 1933 spolu so Schrödingerom; zvažoval ju odmietnuť kvôli publicite, kým mu Rutherford nepovedal, že odmietnutie by vzbudilo ešte väčšiu.',
      'Dirac’s relativistic equation (1928) had solutions with negative energy. Eventually (1931) Dirac saw a new particle in them — the anti-electron. Anderson found it in cosmic rays in 1932 (the positron). Dirac shared the 1933 Nobel Prize with Schrödinger; he considered declining it because of the publicity, until Rutherford told him that declining would attract even more.'],
    quote: ['„To nebola otázka, to bol komentár.“ — anekdota: Dirac, keď sa ho na prednáške ktosi „opýtal“, že nerozumie rovnici vpravo hore', '“That was not a question, it was a comment.” — anecdote: Dirac, after someone in a lecture said they did not understand the equation in the top right'] },

  // ---------- 6 · Rabiho rezonátor ----------
  { id: 's6a', level: 6, step: 'intro', year: '1896 · 1902', people: 'Pieter Zeeman, Hendrik Lorentz',
    title: ['Čiary, ktoré sa rozštiepili', 'Lines that split'],
    text: ['Zeeman (1896) vložil plameň so sodíkom medzi póly elektromagnetu a spektrálne čiary sa rozšírili, neskôr rozštiepili. Lorentz to hneď vysvetlil pohybom nabitých častíc v atóme a z rozštiepenia odhadol pomer náboja a hmotnosti — zhruba v čase, keď Thomson objavil elektrón (1897). Nobelova cena 1902. Tzv. „anomálny“ Zeemanov jav vysvetlil až spin.',
      'Zeeman (1896) placed a sodium flame between the poles of an electromagnet and the spectral lines broadened, later split. Lorentz explained it at once by the motion of charged particles in the atom and estimated their charge-to-mass ratio from the splitting — at about the time Thomson discovered the electron (1897). Nobel Prize 1902. The so-called “anomalous” Zeeman effect was explained only by spin.'],
    quote: ['„Anomálny Zeemanov jav… ako môže človek vyzerať šťastne, keď myslí na anomálny Zeemanov jav?“ — Pauli, okolo 1923', '“How can one look happy when one is thinking about the anomalous Zeeman effect?” — Pauli, around 1923'] },
  { id: 's6b', level: 6, step: 'piPulse', year: '1938 · 1944', people: 'I. I. Rabi, Jerrold Zacharias, Sidney Millman, Polykarp Kusch',
    title: ['Atómy počúvajú rádio', 'Atoms listen to the radio'],
    text: ['Na Kolumbijskej univerzite (1938) Rabiho skupina posielala molekulový zväzok cez statické pole a oscilujúce rádiové pole. Pri presnej frekvencii sa spiny preklopili a zväzok sa minul detektora — prvé meranie magnetickej rezonancie. Nobelova cena 1944. Z metódy vzišli atómové hodiny, NMR aj MRI.',
      'At Columbia University (1938) Rabi’s group sent a molecular beam through a static field and an oscillating radio-frequency field. At exactly the right frequency the spins flipped and the beam missed the detector — the first measurement of magnetic resonance. Nobel Prize 1944. Atomic clocks, NMR and MRI all grew out of the method.'],
    quote: ['„Kto si to objednal?“ — Rabi o objave miónu (1936), častice, ktorú nikto nečakal', '“Who ordered that?” — Rabi on the discovery of the muon (1936), a particle nobody expected'] },
  { id: 's6c', level: 6, step: 't2', year: '1950 · 1973 · 2001', people: 'Erwin Hahn; Paul Lauterbur, Peter Mansfield; Lieven Vandersypen, Isaac Chuang a kol.',
    title: ['Echo, obraz tela a Shor v skúmavke', 'An echo, an image of the body, and Shor in a test tube'],
    text: ['Hahn (1950) objavil spinové echo — π-impulz obráti rozbiehanie fáz a stratený signál sa vráti. Lauterbur (1973) a Mansfield z NMR urobili zobrazovanie (MRI; Nobelova cena 2003). V roku 2001 tím IBM a Stanfordu (Vandersypen, Chuang a kol.) v NMR molekule so 7 jadrovými spinmi spustil Shorov algoritmus a rozložil 15 = 3 × 5.',
      'Hahn (1950) discovered the spin echo — a π pulse reverses the dephasing and the lost signal comes back. Lauterbur (1973) and Mansfield turned NMR into imaging (MRI; Nobel Prize 2003). In 2001 a team at IBM and Stanford (Vandersypen, Chuang et al.) ran Shor’s algorithm in an NMR molecule with 7 nuclear spins and factored 15 = 3 × 5.'],
    quote: ['„Echo bola náhoda — impulzy, ktoré som dával z iných dôvodov, vyrobili signál, ktorý tam nemal byť.“ — parafráza Hahnových spomienok', '“The echo was an accident — pulses I applied for other reasons produced a signal that should not have been there.” — a paraphrase of Hahn’s recollection'] },

  // ---------- 7 · Bellov most ----------
  { id: 's7a', level: 7, step: 'intro', year: '1926 · 1935', people: 'Albert Einstein, Boris Podolsky, Nathan Rosen, Niels Bohr',
    title: ['Boh nehrá kocky?', 'God does not play dice?'],
    text: ['V liste Maxovi Bornovi (1926) Einstein odmietol, že by príroda bola v podstate náhodná. V máji 1935 vyšiel článok EPR „Môže byť kvantovomechanický opis fyzikálnej reality považovaný za úplný?“. Bohr odpovedal v októbri 1935 článkom s <i>rovnakým</i> názvom: o realite nemožno hovoriť bez experimentálneho usporiadania.',
      'In a letter to Max Born (1926) Einstein rejected the idea that nature is fundamentally random. In May 1935 the EPR paper appeared: “Can Quantum-Mechanical Description of Physical Reality Be Considered Complete?”. Bohr replied in October 1935 with a paper of the <i>same</i> title: one cannot speak of reality without the experimental arrangement.'],
    quote: ['„Teória prináša veľa, ale k tajomstvu Starého nás sotva približuje. Ja som v každom prípade presvedčený, že On nehádže kockami.“ — Einstein Bornovi, 4. 12. 1926', '“The theory says a lot, but does not really bring us any closer to the secret of the Old One. I, at any rate, am convinced that He does not throw dice.” — Einstein to Born, 4 Dec 1926'] },
  { id: 's7b', level: 7, step: 'build', year: '1935 · 1947', people: 'Erwin Schrödinger, Albert Einstein',
    title: ['Verschränkung a strašidlá', 'Verschränkung and spooks'],
    text: ['V lete 1935 si Schrödinger s Einsteinom vymieňali listy o EPR. Schrödinger pre jav vymyslel slovo <i>Verschränkung</i> — previazanosť (entanglement) — a v tom istom roku aj mačku v krabici. Einstein ešte v roku 1947 písal Bornovi o „strašidelnom pôsobení na diaľku“ (<i>spukhafte Fernwirkung</i>).',
      'In the summer of 1935 Schrödinger and Einstein exchanged letters about EPR. Schrödinger coined the word <i>Verschränkung</i> — entanglement — for the phenomenon, and in the same year also the cat in the box. As late as 1947 Einstein wrote to Born about “spooky action at a distance” (<i>spukhafte Fernwirkung</i>).'],
    quote: ['„Nenazval by som to jednou, ale skôr <i>tou</i> charakteristickou črtou kvantovej mechaniky, ktorá si vynucuje úplný odklon od klasického myslenia.“ — Schrödinger o previazanosti, 1935', '“I would not call that one but rather <i>the</i> characteristic trait of quantum mechanics, the one that enforces its entire departure from classical lines of thought.” — Schrödinger on entanglement, 1935'] },
  { id: 's7c', level: 7, step: 'chsh', year: '1964 · 1969 · 1982 · 2015 · 2022', people: 'John Bell; Clauser, Horne, Shimony, Holt; Alain Aspect; Anton Zeilinger',
    title: ['Od nerovnosti k Nobelovej cene', 'From an inequality to a Nobel Prize'],
    text: ['Bell (1964, počas tvorivej dovolenky v USA) odvodil nerovnosť, ktorú musí spĺňať každá lokálna teória so skrytými premennými. CHSH (1969) ju upravili pre reálne prístroje; Freedman a Clauser (1972) ju prvýkrát porušili. Aspect (1982) prepínal analyzátory počas letu fotónov. V roku 2015 tri tímy (Delft, Viedeň, NIST) uzavreli hlavné „diery“ naraz. Nobelova cena 2022: Aspect, Clauser, Zeilinger.',
      'Bell (1964, during a sabbatical in the USA) derived an inequality that every local hidden-variable theory must satisfy. CHSH (1969) adapted it for real instruments; Freedman and Clauser (1972) violated it for the first time. Aspect (1982) switched the analysers while the photons were in flight. In 2015 three teams (Delft, Vienna, NIST) closed the main “loopholes” simultaneously. Nobel Prize 2022: Aspect, Clauser, Zeilinger.'],
    quote: ['„V roku 1952 som však uvidel nemožné urobené.“ — Bell o Bohmovej teórii, ktorá vyvracala „dôkaz“ von Neumanna proti skrytým premenným', '“But in 1952 I saw the impossible done.” — Bell on Bohm’s theory, which refuted von Neumann’s “proof” against hidden variables'] },

  // ---------- 8 · Sieň výkladov ----------
  { id: 's8a', level: 8, step: 'intro', year: '1927', people: 'Niels Bohr, Werner Heisenberg, Albert Einstein',
    title: ['Como a Solvay', 'Como and Solvay'],
    text: ['V septembri 1927 Bohr v Como prvýkrát predstavil komplementaritu; Heisenberg v tom istom roku publikoval princíp neurčitosti. O mesiac neskôr, na 5. Solvayovom kongrese v Bruseli, Einstein každé ráno pri raňajkách predkladal myšlienkový pokus, ktorý mal neurčitosť obísť — a Bohr do večera našiel chybu. Na 6. kongrese (1930) Bohr Einsteinovu „fotónovú krabicu“ vyvrátil Einsteinovou vlastnou všeobecnou relativitou.',
      'In September 1927 at Como, Bohr presented complementarity for the first time; Heisenberg published the uncertainty principle the same year. A month later, at the 5th Solvay Conference in Brussels, Einstein proposed every morning at breakfast a thought experiment meant to beat the uncertainty principle — and by evening Bohr had found the flaw. At the 6th conference (1930) Bohr refuted Einstein’s “photon box” using Einstein’s own general relativity.'],
    quote: ['„Einstein, prestaň hovoriť Bohu, čo má robiť!“ — Bohr (podľa svedkov Solvayovho kongresu, 1927)', '“Einstein, stop telling God what to do!” — Bohr (as recalled by witnesses of the Solvay Conference, 1927)'] },
  { id: 's8b', level: 8, step: 'statues', year: '1781 · 1918 · 1921 · 1958', people: 'Immanuel Kant, Emmy Noether, Ludwig Wittgenstein, Werner Heisenberg',
    title: ['Myslitelia v sieni', 'The thinkers in the hall'],
    text: ['Kant: <i>Kritika čistého rozumu</i> (1781). Noetherová: veta o symetriách a zákonoch zachovania, <i>Invariante Variationsprobleme</i> (1918) — Einstein ju v nekrológu (1935) nazval najvýznamnejším tvorivým matematickým géniom od začiatku vysokoškolského vzdelávania žien. Wittgenstein: <i>Tractatus Logico-Philosophicus</i> (1921), veta 5.6 o hraniciach jazyka. Heisenberg: <i>Physics and Philosophy</i> (1958), Giffordove prednášky.',
      'Kant: <i>Critique of Pure Reason</i> (1781). Noether: the theorem on symmetries and conservation laws, <i>Invariante Variationsprobleme</i> (1918) — in his 1935 obituary Einstein called her the most significant creative mathematical genius since the higher education of women began. Wittgenstein: <i>Tractatus Logico-Philosophicus</i> (1921), proposition 5.6 on the limits of language. Heisenberg: <i>Physics and Philosophy</i> (1958), the Gifford Lectures.'],
    quote: ['„To, čo pozorujeme, nie je príroda sama osebe, ale príroda vystavená nášmu spôsobu kladenia otázok.“ — Heisenberg, 1958', '“What we observe is not nature itself, but nature exposed to our method of questioning.” — Heisenberg, 1958'] },
  { id: 's8c', level: 8, step: 'sorting', year: '1932 · 1952 · 1957 · 1989', people: 'John von Neumann, David Bohm, Hugh Everett III, N. David Mermin',
    title: ['Výklady sa množia', 'Interpretations multiply'],
    text: ['Von Neumann (1932) zaviedol do formalizmu „kolaps“ (projekciu) a údajný dôkaz nemožnosti skrytých premenných. Bohm (1952) ho obišiel nelokálnou pilotnou vlnou. Everett (1957, dizertácia) navrhol, že k žiadnemu kolapsu nedochádza (neskôr „mnohosvetová“ interpretácia). Mermin (1989) zhrnul postoj mnohých fyzikov vetou, ktorá sa mylne pripisuje Feynmanovi.',
      'Von Neumann (1932) put “collapse” (projection) into the formalism, together with an alleged proof that hidden variables are impossible. Bohm (1952) got around it with a non-local pilot wave. Everett (1957, PhD thesis) proposed that no collapse happens at all (later the “many-worlds” interpretation). Mermin (1989) summed up many physicists’ attitude with a phrase often misattributed to Feynman.'],
    quote: ['„Ak by som mal jednou vetou zhrnúť, čo mi kodanská interpretácia hovorí, bolo by to: ‚Drž hubu a počítaj!‘“ — N. David Mermin, Physics Today, 1989', '“If I were forced to sum up in one sentence what the Copenhagen interpretation says to me, it would be ‘Shut up and calculate!’” — N. David Mermin, Physics Today, 1989'] },
];

// jedna otázka z histórie na konci každého levelu (prastará)
const TRAPS_ANCIENT = {
  1: [{ q: 'Kto prvý zaviedol pravidlá počítania s odmocninami záporných čísel?', options: ['Rafael Bombelli (1572)', 'Isaac Newton (1687)', 'Carl F. Gauss (1831)'], correct: 0, why: 'Bombelli v L’Algebra (1572); Gauss neskôr spopularizoval názov „komplexné čísla“.' },
    { q: 'Who first gave rules for calculating with square roots of negative numbers?', options: ['Rafael Bombelli (1572)', 'Isaac Newton (1687)', 'Carl F. Gauss (1831)'], correct: 0, why: 'Bombelli in L’Algebra (1572); Gauss later popularised the name “complex numbers”.' }],
  2: [{ q: 'Čo podľa Sternovej spomienky zviditeľnilo stopu striebra?', options: ['síra z lacnej cigary', 'ultrafialová lampa', 'fotografická emulzia'], correct: 0, why: 'Sulfid striebra je čierny — vrstva sa stala viditeľnou (Friedrich a Herschbach to v roku 2003 zopakovali).' },
    { q: 'According to Stern’s recollection, what made the silver trace visible?', options: ['sulphur from a cheap cigar', 'an ultraviolet lamp', 'a photographic emulsion'], correct: 0, why: 'Silver sulphide is black — the layer became visible (Friedrich and Herschbach repeated it in 2003).' }],
  3: [{ q: 'Kto spolu s Blochom dostal Nobelovu cenu 1952 za jadrovú magnetickú rezonanciu?', options: ['Edward Purcell', 'Richard Feynman', 'Max Born'], correct: 0, why: 'Bloch (Stanford) a Purcell (Harvard) objavili NMR v látkach nezávisle v roku 1946.' },
    { q: 'Who shared the 1952 Nobel Prize with Bloch for nuclear magnetic resonance?', options: ['Edward Purcell', 'Richard Feynman', 'Max Born'], correct: 0, why: 'Bloch (Stanford) and Purcell (Harvard) independently discovered NMR in matter in 1946.' }],
  4: [{ q: 'Kto prvý ukázal interferenciu svetla za dvoma štrbinami?', options: ['Thomas Young (1801–1803)', 'Isaac Newton (1704)', 'Richard Feynman (1965)'], correct: 0, why: 'Young — a tým podporil vlnovú teóriu svetla proti Newtonovej korpuskulárnej.' },
    { q: 'Who first demonstrated the interference of light behind two slits?', options: ['Thomas Young (1801–1803)', 'Isaac Newton (1704)', 'Richard Feynman (1965)'], correct: 0, why: 'Young — thereby supporting the wave theory of light against Newton’s corpuscular one.' }],
  5: [{ q: 'Ktorú časticu predpovedala Diracova rovnica a kto ju objavil?', options: ['pozitrón — Carl Anderson (1932)', 'neutrón — James Chadwick (1932)', 'mión — Rabiho tím (1936)'], correct: 0, why: 'Riešenia so zápornou energiou → anti-elektrón, nájdený v kozmickom žiarení v roku 1932.' },
    { q: 'Which particle did the Dirac equation predict, and who found it?', options: ['the positron — Carl Anderson (1932)', 'the neutron — James Chadwick (1932)', 'the muon — Rabi’s team (1936)'], correct: 0, why: 'Negative-energy solutions → the anti-electron, found in cosmic rays in 1932.' }],
  6: [{ q: 'Kto (2001) spustil Shorov algoritmus v NMR a čo rozložil?', options: ['tím IBM a Stanfordu — 15 = 3 × 5', 'Rabi — 21 = 3 × 7', 'Bloch a Purcell — 6 = 2 × 3'], correct: 0, why: 'Vandersypen, Chuang a kol.: molekula so 7 jadrovými spinmi, Nature 2001.' },
    { q: 'Who ran Shor’s algorithm in NMR in 2001, and what did they factor?', options: ['an IBM–Stanford team — 15 = 3 × 5', 'Rabi — 21 = 3 × 7', 'Bloch and Purcell — 6 = 2 × 3'], correct: 0, why: 'Vandersypen, Chuang et al.: a molecule with 7 nuclear spins, Nature 2001.' }],
  7: [{ q: 'Kto vymyslel slovo „previazanosť“ (Verschränkung) a kedy?', options: ['Erwin Schrödinger, 1935', 'Albert Einstein, 1926', 'John Bell, 1964'], correct: 0, why: 'V korešpondencii s Einsteinom a v článkoch roku 1935, po článku EPR.' },
    { q: 'Who coined the word “entanglement” (Verschränkung), and when?', options: ['Erwin Schrödinger, 1935', 'Albert Einstein, 1926', 'John Bell, 1964'], correct: 0, why: 'In his correspondence with Einstein and in his 1935 papers, after the EPR paper.' }],
  8: [{ q: 'Kde a kedy Bohr prvýkrát predstavil komplementaritu?', options: ['Como, september 1927', 'Kodaň, 1913', 'Brusel, 1930'], correct: 0, why: 'Prednáška na konferencii k Voltovmu výročiu v Como; o mesiac neskôr nasledoval Solvayov kongres.' },
    { q: 'Where and when did Bohr first present complementarity?', options: ['Como, September 1927', 'Copenhagen, 1913', 'Brussels, 1930'], correct: 0, why: 'A lecture at the Volta centenary conference in Como; the Solvay Conference followed a month later.' }],
};

function scrollFor(num, step) { return Settings.diff === 'ancient' ? SCROLLS.filter((s) => s.level === num && s.step === step) : []; }
function scrollHtml(s) {
  return `<div class="scroll-head"><b>${s.year}</b> · ${s.people}</div><div class="scroll-title">${pick(s.title)}</div>`
    + `<div>${pick(s.text)}</div><blockquote>${pick(s.quote)}</blockquote>`;
}
function ancientTraps(num) { return Settings.diff === 'ancient' && TRAPS_ANCIENT[num] ? [pick(TRAPS_ANCIENT[num])] : []; }
