'use strict';
// Krátke vysvetlivky pri prejdení myšou: symboly, tlačidlá, 3D popisky a pojmy v dialógoch.

// Presné zhody (text popisky alebo tlačidla bez HTML)
const TIPS_SK = {
  // stavy a symboly
  '|0⟩': 'Bázový stav |0⟩ ≡ |+z⟩ („spin hore“). Severný pól Blochovej sféry. Nie je to nulový vektor!',
  '|1⟩': 'Bázový stav |1⟩ ≡ |−z⟩ („spin dole“). Južný pól. S |0⟩ je ortogonálny (v Hilbertovom priestore kolmý, na sfére protiľahlý).',
  '|+⟩': '|+⟩ = (|0⟩ + |1⟩)/√2 — rovník, os +x. V Z-báze 50/50, v X-báze vždy „+“.',
  '|−⟩': '|−⟩ = (|0⟩ − |1⟩)/√2 — os −x. Od |+⟩ sa líši len relatívnou fázou π.',
  '|+i⟩': '|+i⟩ = (|0⟩ + i|1⟩)/√2 — os +y. Relatívna fáza π/2; dôkaz, že amplitúdy musia byť komplexné.',
  '|−i⟩': '|−i⟩ = (|0⟩ − i|1⟩)/√2 — os −y. Relatívna fáza −π/2.',
  'ψ': 'ψ (psí) — kvantový stav. To si ty, Psíčko: nie guľôčka, ale pravidlo pre predpovede výsledkov meraní.',
  'x': 'Os x Blochovej sféry — smer stavu |+⟩. Nie je to smer v laboratóriu!',
  'y': 'Os y Blochovej sféry — smer stavu |+i⟩.',
  'z': 'Os z Blochovej sféry — smer stavu |0⟩. Meranie „v Z-báze“ = otázka „|0⟩ alebo |1⟩?“.',
  'Re': 'Reálna časť komplexného čísla (vodorovná os komplexnej roviny).',
  'Im': 'Imaginárna časť komplexného čísla (zvislá os). V QM ju nezahadzuj — nesie fázu.',
  '1': 'Číslo 1 v komplexnej rovine (fáza 0).',
  'i': 'Imaginárna jednotka: i² = −1. Násobenie i = otočenie o 90°.',
  '−1': '−1 = e^{iπ}: otočenie o 180°. Toto „mínus“ odlišuje |+⟩ od |−⟩.',
  '−i': '−i = e^{−iπ/2} = i³: otočenie o 270°.',
  'α': 'Amplitúda α — komplexné číslo s veľkosťou a fázou. Pravdepodobnosť je |α|², nie α.',
  'A₁': 'Amplitúda prvej cesty.',
  'A₂': 'Amplitúda druhej cesty — jej fázu meníš posuvníkom.',
  'A₁+A₂': 'Celková amplitúda: najprv sa sčítajú amplitúdy, až potom umocníme → interferencia.',
  'P = |α|²': 'Bornovo pravidlo: pravdepodobnosť = štvorec absolútnej hodnoty amplitúdy. Fázu „nevidí“.',
  'B₀': 'Statické magnetické pole NMR magnetu. Rozštiepi energiu spinu na dve Zeemanove hladiny = qubit.',
  '+ħ/2': 'Výsledok merania S_z = +ħ/2 („spin hore“, stav |0⟩). ħ = h/2π.',
  '−ħ/2': 'Výsledok merania S_z = −ħ/2 („spin dole“, stav |1⟩).',
  'tienidlo': 'Tu dopadajú atómy. Každý atóm = jeden výsledok merania (jedna bodka).',
  'stav na konci': 'Blochova sféra qubitu po prejdení koľajou: šípka = čistý stav, bod v strede = maximálne zmiešaný stav I/2.',
  'matica hustoty ρ': 'ρ (ró): úplný opis stavu aj so zmesami. Diagonála = populácie, mimodiagonála = koherencie.',
  '(prázdne)': 'Stred chrámu je prázdny — nič neruší koherenciu.',
  'H': 'Hadamardovo hradlo: rotácia o 180° okolo osi medzi x a z. Vymieňa osi x ↔ z. H·H = I.',
  'X': 'Pauliho X: rotácia o 180° okolo osi x — preklopenie bitu (kvantové NOT).',
  'Y': 'Pauliho Y: rotácia o 180° okolo osi y. Y|0⟩ = i|1⟩ ∼ |1⟩.',
  'Z': 'Pauliho Z: rotácia o 180° okolo osi z — preklopenie fázy. P(0), P(1) v Z-báze sa nezmenia.',
  'S': 'Fázové hradlo S: rotácia o 90° okolo osi z (pridá fázu i k |1⟩).',
  'T': 'Hradlo T: rotácia o 45° okolo osi z (fáza e^{iπ/4}).',
  '|ψ⟩': 'Ket — abstraktný stav (stĺpcový vektor). Tvar v 3D: šípka.',
  '|φ⟩': 'Ket — iný stav φ.',
  '|a⟩': 'Ket — vlastný stav a (napr. výsledok merania).',
  '⟨ψ|': 'Bra — duálny (hermitovsky združený) vektor, riadok. „Kladie otázku.“ Tvar: doska.',
  '⟨φ|': 'Bra stavu φ.',
  '⟨a|': 'Bra stavu a — otázka „je to stav a?“.',
  'Â': 'Operátor (strieška) — pozorovateľná veličina, „stroj“ meniaci kety. Tvar: kocka.',
  'Ĥ': 'Hamiltonián — operátor energie; určuje časový vývoj stavu.',
  '⊗': 'Tenzorový súčin — skladá dva systémy do jedného: |0⟩ ⊗ |1⟩ = |01⟩.',
  '|…|²': 'Štvorec absolútnej hodnoty: z amplitúdy (čísla) urobí pravdepodobnosť. Na kety ani operátory sa nedá použiť.',
  '⌫': 'Zmaže posledný token.',
  'Alica': 'Alica — majiteľka qubitu A. Meria lokálne, bez spojenia s Bobom.',
  'Bob': 'Bob — majiteľ qubitu B. Jeho štatistika je vždy 50/50, nech Alica robí čokoľvek.',
  'a₀': 'Uhol merania Alice, keď dostane x = 0.', 'a₁': 'Uhol merania Alice, keď dostane x = 1.',
  'b₀': 'Uhol merania Boba, keď dostane y = 0.', 'b₁': 'Uhol merania Boba, keď dostane y = 1.',
  'rotujúci rámec': 'Súradnice otáčajúce sa s Larmorovou frekvenciou — rýchla precesia „zastane“. Matematický trik.',
  'laboratórny rámec': 'Pohľad z laboratória: spin precesuje okolo B₀ (mení sa fáza, nie P(0), P(1)).',
  'RF cievka': 'Rádiofrekvenčná cievka: vysiela impulzy, ktoré otáčajú Blochov vektor (hradlá v NMR).',
  'RF impulz!': 'Beží rezonančný impulz: stav sa otáča okolo osi v rovine xy (Rabiho oscilácia).',
  'vzorka (ansámbel molekúl)': 'V NMR meriame naraz obrovské množstvo molekúl → signál = stredná hodnota.',
  '🔗 korelácie (nie signál!)': 'Previazanosť: výsledky sú korelované, ale nedá sa ňou poslať správa.',
  '[E] Hovoriť s Amplitúdou': 'Sprievodkyňa ti pripomenie cieľ a ďalší krok.',
};

// Tlačidlá a popisky podľa obsiahnutého textu
const TIP_PATTERNS_SK = [
  [/^SG/, 'Sternov–Gerlachov magnet: nehomogénne pole rozdelí zväzok podľa projekcie spinu do svojej osi. Os vyberá OTÁZKU.'],
  [/^pec/, 'Pec: odparuje striebro. Atómy letia nepolarizované — maximálne zmiešaný stav (žiadna preferovaná os).'],
  [/Klasický model/, 'Čo by sme čakali, keby magnetíky mali náhodnú klasickú orientáciu: spojitý pás.'],
  [/Skutočnosť/, 'Skutočné (kvantové) správanie: len dve stopy.'],
  [/Vystreľ/, 'Pošle atómy z pece cez magnety na tienidlo.'],
  [/Zostava A/, 'Z+ → Z: prvý magnet prepustí len „+“, druhý znova meria Z.'],
  [/Zostava B/, 'Z+ → X+ → Z: medzi dve merania Z vložíme meranie X.'],
  [/^Magnet \d/, 'Zapni/vypni magnet. Posuvník = os merania (0° = z, 90° = x), filter = ktorý zväzok prejde.'],
  [/× i/, 'Vynásob amplitúdu číslom i = otoč ručičku o 90° proti smeru hodín.'],
  [/Znova/, 'Začni hádanku odznova.'],
  [/Meraj 1×/, 'Jedno meranie v Z-báze: dá jeden bit a stav „skolabuje“ na |0⟩ alebo |1⟩.'],
  [/Meraj 100 kópií/, '100 rovnako pripravených kópií, každá zmeraná raz — tak sa zisťujú pravdepodobnosti.'],
  [/Priprav/, 'Priprav nový stav (nová kópia qubitu).'],
  [/Pošli 1/, 'Pošli jeden qubit pomaly — sleduj, ako sa mení Blochova šípka a matica ρ na každej stanici.'],
  [/Pošli 100/, 'Pošli 100 qubitov naraz a pozri štatistiku detektora.'],
  [/Vymaž/, 'Vynuluje počítadlá / výraz.'],
  [/Over/, 'Skontroluj, či postavený výraz zodpovedá úlohe.'],
  [/Impulz z/, 'Resetuje spin do |0⟩ a pustí RF impulz s nastavenou plochou (= uhol rotácie).'],
  [/Reset/, 'Vráti stav na začiatok.'],
  [/CNOT/, 'Riadené NOT: ak je A v |1⟩, preklopí B. Po H na A vyrobí previazaný Bellov stav.'],
  [/H na [AB]/, 'Hadamard na jeden qubit.'], [/X na [AB]/, 'Preklopenie bitu jedného qubitu.'],
  [/Meraj 200/, 'Zmeria 200 previazaných párov v zvolených bázach.'],
  [/Hraj 400/, 'Odohrá 400 kôl CHSH hry s tvojimi uhlami a previazaným párom.'],
  [/Klasicky/, 'Najlepšia klasická stratégia: vždy odpovedať 0 → 75 %.'],
  [/Nápoveda/, 'Ukáže optimálne uhly.'],
  [/Laboratórny rámec/, 'Pozeráš z laboratória: spin precesuje okolo B₀.'], [/Rotujúci rámec/, 'Točíš sa so spinom — precesia zmizne.'],
  [/Ostrov/, 'Späť na Hilbertov ostrov (rozpracovaný level sa začne odznova).'],
  [/Mapa/, 'Mapa ostrova s portálmi (M).'], [/Kódex/, 'Odomknuté symboly, osobnosti a pojmy (C).'], [/Denník/, 'Všetky dialógy a vysvetlenia — prečítaj alebo prehraj znova (L).'],
  [/Amplitúda/, 'Sprievodkyňa Amplitúda — komplexné číslo, ktoré ťa vedie ostrovom.'],
  [/^ρ|^\|ρ/, 'Prvok matice hustoty: ρ₀₀, ρ₁₁ = pravdepodobnosti (populácie), |ρ₀₁| = koherencia (pamäť fázy).'],
  [/^\d: \d+/, 'Počet výsledkov 0 alebo 1 na detektore.'],
  [/príprava/, 'Qubit vždy štartuje v stave |0⟩.'],
  [/meranie Z/, 'Meranie v Z-báze s ZABUDNUTÝM výsledkom — zničí koherenciu, zostane zmes.'],
  [/prostredie/, 'Dekoherencia: prostredie čiastočne „odmeria“ fázu; koherencie sa zmenšia o faktor (1 − p).'],
  [/^os /, 'Os rotácie práve vykonávaného hradla.'],
];

// Pojmy, ktoré sa v dialógoch podčiarknu (kmeň slova → vysvetlivka)
const GLOSS_SK = [
  ['amplitúd', 'Amplitúda: komplexné číslo pri výsledku; pravdepodobnosť je jej |…|².'],
  ['superpozíci', 'Superpozícia: lineárna kombinácia stavov. Nie je to „nevieme, v ktorom je“ ani paralelné počítanie.'],
  ['dekoherenci', 'Dekoherencia: prostredie ničí fázové vzťahy (koherencie); šípka sa zmršťuje dovnútra gule.'],
  ['koherenci', 'Koherencia: pevný fázový vzťah medzi zložkami stavu — umožňuje interferenciu.'],
  ['interferenci', 'Interferencia: sčítanie amplitúd pred umocnením; podľa fázy zosilnenie alebo vyrušenie.'],
  ['previazan', 'Previazanosť (entanglement): stav celku sa nedá zapísať ako súčin stavov častí.'],
  ['relatívn\\p{L}* fáz', 'Relatívna fáza: fázový rozdiel medzi α a β; pozorovateľná cez meranie v inej báze.'],
  ['globáln\\p{L}* fáz', 'Globálna fáza: spoločný faktor celého stavu; nepozorovateľná.'],
  ['Blochov\\p{L}* sfér', 'Blochova sféra: obraz stavu qubitu; povrch = čisté, vnútro = zmiešané stavy.'],
  ['matic\\p{L}* hustoty', 'Matica hustoty ρ: opis stavu vrátane zmesí; diagonála = populácie, mimo = koherencie.'],
  ['Bornov\\p{L}* pravidl', 'Bornovo pravidlo: P = |amplitúda|².'],
  ['kolaps', 'Kolaps: prechod od kvantovej možnosti ku klasickému faktu pri meraní (readout).'],
  ['Hamiltoni', 'Hamiltonián Ĥ: operátor energie, ktorý určuje časový vývoj.'],
  ['unitárn', 'Unitárna operácia: vratná, zachováva normu; na Blochovej sfére rotácia.'],
  ['báz', 'Báza: súbor ortogonálnych stavov = „otázka“, ktorú meraním kladieme (napr. Z: |0⟩ alebo |1⟩?).'],
  ['operátor', 'Operátor: „stroj“, ktorý mení stavy; pozorovateľné veličiny sú hermitovské operátory.'],
  ['stredn\\p{L}* hodnot', 'Stredná hodnota ⟨A⟩: priemer mnohých meraní, nie výsledok jedného.'],
  ['precesi', 'Precesia: vývoj relatívnej fázy v poli B₀; P(0), P(1) sa nemenia.'],
  ['rezonanci', 'Rezonancia: frekvencia budenia sa zhoduje s prirodzenou frekvenciou systému.'],
  ['komplementarit', 'Komplementarita (Bohr): vlnový a časticový opis sa dopĺňajú podľa experimentu; nie relativizmus.'],
  ['zmes', 'Zmes: štatistická neznalosť (klasická); nemá koherencie, neinterferuje.'],
  ['zmiešan', 'Zmiešaný stav: |r| < 1, vnútri Blochovej sféry.'],
  ['ortogonáln', 'Ortogonálne stavy: skalárny súčin 0, dokonale rozlíšiteľné meraním.'],
  ['spin', 'Spin: kvantová forma vnútorného momentu hybnosti — nie rotujúca guľôčka.'],
  ['qubit', 'Qubit: kvantový systém s dvojrozmerným komplexným stavovým priestorom.'],
  ['ket', 'Ket |ψ⟩: zápis stavu (stĺpcový vektor).'],
  ['ansámb', 'Ansámbel: veľký súbor rovnako pripravených systémov; NMR meria jeho priemer.'],
  ['nelokáln', 'Nelokálnosť: vplyv medzi vzdialenými miestami bez sprostredkovania v priestore.'],
  ['skryt\\p{L}* premenn', 'Skryté premenné: hypotetické hodnoty určené pred meraním (Bohm). Lokálne vylúčil Bell.'],
  ['hradl', 'Hradlo: elementárna kvantová operácia (unitárna rotácia).'],
];
// ---------- English ----------
const TIPS_EN = {
  '|0⟩': 'Basis state |0⟩ ≡ |+z⟩ (“spin up”). North pole of the Bloch sphere. It is not the zero vector!',
  '|1⟩': 'Basis state |1⟩ ≡ |−z⟩ (“spin down”). South pole. Orthogonal to |0⟩ (perpendicular in Hilbert space, antipodal on the sphere).',
  '|+⟩': '|+⟩ = (|0⟩ + |1⟩)/√2 — equator, +x axis. 50/50 in the Z basis, always “+” in the X basis.',
  '|−⟩': '|−⟩ = (|0⟩ − |1⟩)/√2 — −x axis. Differs from |+⟩ only by the relative phase π.',
  '|+i⟩': '|+i⟩ = (|0⟩ + i|1⟩)/√2 — +y axis. Relative phase π/2; proof that amplitudes must be complex.',
  '|−i⟩': '|−i⟩ = (|0⟩ − i|1⟩)/√2 — −y axis. Relative phase −π/2.',
  'ψ': 'ψ (psi) — a quantum state. That’s you, Little Psi: not a little ball, but a rule for predicting measurement outcomes.',
  'x': 'The x axis of the Bloch sphere — direction of the state |+⟩. Not a direction in the lab!',
  'y': 'The y axis of the Bloch sphere — direction of the state |+i⟩.',
  'z': 'The z axis of the Bloch sphere — direction of the state |0⟩. Measuring “in the Z basis” = asking “|0⟩ or |1⟩?”.',
  'Re': 'Real part of a complex number (horizontal axis of the complex plane).',
  'Im': 'Imaginary part of a complex number (vertical axis). Don’t throw it away in QM — it carries the phase.',
  '1': 'The number 1 in the complex plane (phase 0).',
  'i': 'Imaginary unit: i² = −1. Multiplying by i = rotating by 90°.',
  '−1': '−1 = e^{iπ}: rotation by 180°. This “minus” distinguishes |+⟩ from |−⟩.',
  '−i': '−i = e^{−iπ/2} = i³: rotation by 270°.',
  'α': 'Amplitude α — a complex number with a magnitude and a phase. The probability is |α|², not α.',
  'A₁': 'Amplitude of the first path.',
  'A₂': 'Amplitude of the second path — you change its phase with the slider.',
  'A₁+A₂': 'Total amplitude: first the amplitudes add, only then we square → interference.',
  'P = |α|²': 'Born rule: probability = squared absolute value of the amplitude. It does not “see” the phase.',
  'B₀': 'Static magnetic field of the NMR magnet. Splits the spin energy into two Zeeman levels = a qubit.',
  '+ħ/2': 'Outcome of measuring S_z = +ħ/2 (“spin up”, state |0⟩). ħ = h/2π.',
  '−ħ/2': 'Outcome of measuring S_z = −ħ/2 (“spin down”, state |1⟩).',
  'screen': 'Atoms land here. Each atom = one measurement outcome (one dot).',
  'final state': 'Bloch sphere of the qubit after the track: an arrow = pure state, a point in the centre = maximally mixed state I/2.',
  'density matrix ρ': 'ρ (rho): complete description of the state including mixtures. Diagonal = populations, off-diagonal = coherences.',
  '(empty)': 'The centre of the temple is empty — nothing disturbs the coherence.',
  'H': 'Hadamard gate: 180° rotation about the axis between x and z. Swaps the axes x ↔ z. H·H = I.',
  'X': 'Pauli X: 180° rotation about the x axis — bit flip (quantum NOT).',
  'Y': 'Pauli Y: 180° rotation about the y axis. Y|0⟩ = i|1⟩ ∼ |1⟩.',
  'Z': 'Pauli Z: 180° rotation about the z axis — phase flip. P(0), P(1) in the Z basis don’t change.',
  'S': 'Phase gate S: 90° rotation about the z axis (adds the phase i to |1⟩).',
  'T': 'T gate: 45° rotation about the z axis (phase e^{iπ/4}).',
  '|ψ⟩': 'Ket — an abstract state (column vector). 3D shape: an arrow.',
  '|φ⟩': 'Ket — another state φ.',
  '|a⟩': 'Ket — eigenstate a (e.g. a measurement outcome).',
  '⟨ψ|': 'Bra — the dual (Hermitian-conjugate) vector, a row. It “asks a question”. Shape: a plank.',
  '⟨φ|': 'Bra of the state φ.',
  '⟨a|': 'Bra of the state a — the question “is it state a?”.',
  'Â': 'Operator (hat) — an observable, a “machine” that transforms kets. Shape: a cube.',
  'Ĥ': 'Hamiltonian — the energy operator; it governs the time evolution of the state.',
  '⊗': 'Tensor product — combines two systems into one: |0⟩ ⊗ |1⟩ = |01⟩.',
  '|…|²': 'Squared absolute value: turns an amplitude (a number) into a probability. Cannot be applied to kets or operators.',
  '⌫': 'Deletes the last token.',
  'Alice': 'Alice — owner of qubit A. She measures locally, with no link to Bob.',
  'Bob': 'Bob — owner of qubit B. His statistics are always 50/50, whatever Alice does.',
  'a₀': 'Alice’s measurement angle when she gets x = 0.', 'a₁': 'Alice’s measurement angle when she gets x = 1.',
  'b₀': 'Bob’s measurement angle when he gets y = 0.', 'b₁': 'Bob’s measurement angle when he gets y = 1.',
  'rotating frame': 'Coordinates rotating at the Larmor frequency — the fast precession “stops”. A mathematical trick.',
  'laboratory frame': 'The view from the lab: the spin precesses about B₀ (the phase changes, not P(0), P(1)).',
  'RF coil': 'Radio-frequency coil: sends pulses that rotate the Bloch vector (the gates of NMR).',
  'RF pulse!': 'A resonant pulse is running: the state rotates about an axis in the xy plane (Rabi oscillation).',
  'sample (ensemble of molecules)': 'In NMR we measure a huge number of molecules at once → signal = expectation value.',
  '🔗 correlations (not a signal!)': 'Entanglement: the outcomes are correlated, but you cannot send a message with it.',
  '[E] Talk to Amplitude': 'Your guide will remind you of the goal and the next step.',
};
const TIPS_UK = {
  '|0⟩': 'Базисний стан |0⟩ ≡ |+z⟩ («спін угору»). Північний полюс сфери Блоха. Це не нульовий вектор!',
  '|1⟩': 'Базисний стан |1⟩ ≡ |−z⟩ («спін униз»). Південний полюс. Ортогональний до |0⟩ (перпендикулярний у гільбертовому просторі, протилежний на сфері).',
  '|+⟩': '|+⟩ = (|0⟩ + |1⟩)/√2 — екватор, вісь +x. У базисі Z 50/50, у базисі X завжди «+».',
  '|−⟩': '|−⟩ = (|0⟩ − |1⟩)/√2 — вісь −x. Від |+⟩ відрізняється лише відносною фазою π.',
  '|+i⟩': '|+i⟩ = (|0⟩ + i|1⟩)/√2 — вісь +y. Відносна фаза π/2; доказ того, що амплітуди мусять бути комплексними.',
  '|−i⟩': '|−i⟩ = (|0⟩ − i|1⟩)/√2 — вісь −y. Відносна фаза −π/2.',
  'ψ': 'ψ (псі) — квантовий стан. Це ти, Псічко: не кулька, а правило для передбачення результатів вимірювань.',
  'x': 'Вісь x сфери Блоха — напрямок стану |+⟩. Це не напрямок у лабораторії!',
  'y': 'Вісь y сфери Блоха — напрямок стану |+i⟩.',
  'z': 'Вісь z сфери Блоха — напрямок стану |0⟩. Вимірювання «в базисі Z» = питання «|0⟩ чи |1⟩?».',
  'Re': 'Дійсна частина комплексного числа (горизонтальна вісь комплексної площини).',
  'Im': 'Уявна частина комплексного числа (вертикальна вісь). У КМ не відкидай її — вона несе фазу.',
  '1': 'Число 1 у комплексній площині (фаза 0).',
  'i': 'Уявна одиниця: i² = −1. Множення на i = поворот на 90°.',
  '−1': '−1 = e^{iπ}: поворот на 180°. Саме цей «мінус» відрізняє |+⟩ від |−⟩.',
  '−i': '−i = e^{−iπ/2} = i³: поворот на 270°.',
  'α': 'Амплітуда α — комплексне число з модулем і фазою. Імовірність — це |α|², а не α.',
  'A₁': 'Амплітуда першого шляху.',
  'A₂': 'Амплітуда другого шляху — її фазу змінюєш повзунком.',
  'A₁+A₂': 'Сумарна амплітуда: спершу амплітуди додаються, лише потім підносимо до квадрата → інтерференція.',
  'P = |α|²': 'Правило Борна: імовірність = квадрат модуля амплітуди. Фази «не бачить».',
  'B₀': 'Статичне магнітне поле ЯМР-магніту. Розщеплює енергію спіну на два зееманівські рівні = кубіт.',
  '+ħ/2': 'Результат вимірювання S_z = +ħ/2 («спін угору», стан |0⟩). ħ = h/2π.',
  '−ħ/2': 'Результат вимірювання S_z = −ħ/2 («спін униз», стан |1⟩).',
  'екран': 'Сюди падають атоми. Кожен атом = один результат вимірювання (одна точка).',
  'кінцевий стан': 'Сфера Блоха кубіта після доріжки: стрілка = чистий стан, точка в центрі = максимально змішаний стан I/2.',
  'матриця густини ρ': 'ρ (ро): повний опис стану, включно із сумішами. Діагональ = заселеності, позадіагональ = когерентності.',
  '(порожньо)': 'Центр храму порожній — ніщо не порушує когерентності.',
  'H': 'Гейт Адамара: поворот на 180° навколо осі між x і z. Міняє осі x ↔ z. H·H = I.',
  'X': 'Паулі X: поворот на 180° навколо осі x — переворот біта (квантове НЕ).',
  'Y': 'Паулі Y: поворот на 180° навколо осі y. Y|0⟩ = i|1⟩ ∼ |1⟩.',
  'Z': 'Паулі Z: поворот на 180° навколо осі z — переворот фази. P(0), P(1) у базисі Z не змінюються.',
  'S': 'Фазовий гейт S: поворот на 90° навколо осі z (додає до |1⟩ фазу i).',
  'T': 'Гейт T: поворот на 45° навколо осі z (фаза e^{iπ/4}).',
  '|ψ⟩': 'Кет — абстрактний стан (вектор-стовпець). 3D-фігура: стрілка.',
  '|φ⟩': 'Кет — інший стан φ.',
  '|a⟩': 'Кет — власний стан a (напр. результат вимірювання).',
  '⟨ψ|': 'Бра — дуальний (ермітово спряжений) вектор, рядок. Він «ставить питання». Фігура: дошка.',
  '⟨φ|': 'Бра стану φ.',
  '⟨a|': 'Бра стану a — питання «чи це стан a?».',
  'Â': 'Оператор (дашок) — спостережувана, «машина», що перетворює кети. Фігура: куб.',
  'Ĥ': 'Гамільтоніан — оператор енергії; керує часовою еволюцією стану.',
  '⊗': 'Тензорний добуток — поєднує дві системи в одну: |0⟩ ⊗ |1⟩ = |01⟩.',
  '|…|²': 'Квадрат модуля: перетворює амплітуду (число) на ймовірність. До кетів чи операторів не застосовується.',
  '⌫': 'Видаляє останній жетон.',
  'Аліса': 'Аліса — власниця кубіта A. Вимірює локально, без зв’язку з Бобом.',
  'Боб': 'Боб — власник кубіта B. Його статистика завжди 50/50, хоч би що робила Аліса.',
  'a₀': 'Кут вимірювання Аліси, коли вона отримує x = 0.', 'a₁': 'Кут вимірювання Аліси, коли вона отримує x = 1.',
  'b₀': 'Кут вимірювання Боба, коли він отримує y = 0.', 'b₁': 'Кут вимірювання Боба, коли він отримує y = 1.',
  'обертова система': 'Координати, що обертаються з ларморовою частотою, — швидка прецесія «зупиняється». Математичний трюк.',
  'лабораторна система': 'Погляд із лабораторії: спін прецесує навколо B₀ (змінюється фаза, а не P(0), P(1)).',
  'РЧ-котушка': 'Радіочастотна котушка: надсилає імпульси, що обертають вектор Блоха (гейти ЯМР).',
  'РЧ-імпульс!': 'Триває резонансний імпульс: стан обертається навколо осі в площині xy (осциляція Рабі).',
  'зразок (ансамбль молекул)': 'У ЯМР ми вимірюємо величезну кількість молекул одночасно → сигнал = середнє значення.',
  '🔗 кореляції (а не сигнал!)': 'Сплутаність: результати корельовані, але надіслати нею повідомлення неможливо.',
  '[E] Поговорити з Амплітудою': 'Твоя провідниця нагадає мету й наступний крок.',
};

const TIP_PATTERNS_EN = [
  [/^SG/, 'Stern–Gerlach magnet: the inhomogeneous field splits the beam by the spin projection onto its axis. The axis chooses the QUESTION.'],
  [/^furnace/, 'Furnace: evaporates silver. The atoms fly out unpolarised — a maximally mixed state (no preferred axis).'],
  [/Classical model/, 'What we would expect if the little magnets had random classical orientations: a continuous band.'],
  [/Reality/, 'Real (quantum) behaviour: only two spots.'],
  [/Fire/, 'Sends atoms from the furnace through the magnets onto the screen.'],
  [/Setup A/, 'Z+ → Z: the first magnet lets only “+” through, the second measures Z again.'],
  [/Setup B/, 'Z+ → X+ → Z: we insert an X measurement between two Z measurements.'],
  [/^Magnet \d/, 'Turn the magnet on/off. Slider = measurement axis (0° = z, 90° = x), filter = which beam passes.'],
  [/× i/, 'Multiply the amplitude by i = turn the hand 90° counter-clockwise.'],
  [/Again/, 'Restart the puzzle.'],
  [/Measure 1×/, 'One measurement in the Z basis: gives one bit and the state “collapses” to |0⟩ or |1⟩.'],
  [/Measure 100 copies/, '100 identically prepared copies, each measured once — that is how probabilities are found.'],
  [/Prepare/, 'Prepare a new state (a new copy of the qubit).'],
  [/Send 1/, 'Send one qubit slowly — watch how the Bloch arrow and the matrix ρ change at each station.'],
  [/Send 100/, 'Send 100 qubits at once and look at the detector statistics.'],
  [/Clear/, 'Resets the counters / the expression.'],
  [/Check/, 'Check whether the built expression matches the task.'],
  [/Pulse from/, 'Resets the spin to |0⟩ and fires an RF pulse with the chosen area (= rotation angle).'],
  [/Reset/, 'Returns the state to the start.'],
  [/CNOT/, 'Controlled NOT: if A is |1⟩, it flips B. After H on A it produces an entangled Bell state.'],
  [/H on [AB]/, 'Hadamard on one qubit.'], [/X on [AB]/, 'Bit flip of one qubit.'],
  [/Measure 200/, 'Measures 200 entangled pairs in the chosen bases.'],
  [/Play 400/, 'Plays 400 rounds of the CHSH game with your angles and an entangled pair.'],
  [/Classically/, 'Best classical strategy: always answer 0 → 75 %.'],
  [/Hint/, 'Shows the optimal angles.'],
  [/Laboratory frame/, 'You look from the lab: the spin precesses about B₀.'], [/Rotating frame/, 'You rotate along with the spin — the precession disappears.'],
  [/Island/, 'Back to Hilbert Island (a level in progress will restart).'],
  [/Map/, 'Island map with the portals (M).'], [/Codex/, 'Unlocked symbols, people and concepts (C).'], [/Journal/, 'All dialogues and explanations — read or replay (L).'],
  [/Amplitude/, 'Your guide Amplitude — a complex number leading you around the island.'],
  [/^ρ|^\|ρ/, 'Density-matrix element: ρ₀₀, ρ₁₁ = probabilities (populations), |ρ₀₁| = coherence (memory of the phase).'],
  [/^\d: \d+/, 'Number of outcomes 0 or 1 at the detector.'],
  [/preparation/, 'The qubit always starts in the state |0⟩.'],
  [/Z measurement/, 'Z-basis measurement with a FORGOTTEN result — destroys coherence, leaves a mixture.'],
  [/environment/, 'Decoherence: the environment partly “measures” the phase; coherences shrink by the factor (1 − p).'],
  [/^axis /, 'Rotation axis of the gate being applied.'],
];
const TIP_PATTERNS_UK = [
  [/^SG/, 'Магніт Штерна–Ґерлаха: неоднорідне поле розщеплює пучок за проєкцією спіну на свою вісь. Вісь обирає ПИТАННЯ.'],
  [/^піч/, 'Піч: випаровує срібло. Атоми вилітають неполяризованими — максимально змішаний стан (жодної переважної осі).'],
  [/Класична модель/, 'Чого ми чекали б, якби магнітики мали випадкові класичні орієнтації: суцільна смуга.'],
  [/Реальність/, 'Реальна (квантова) поведінка: лише дві плями.'],
  [/Постріл/, 'Надсилає атоми з печі крізь магніти на екран.'],
  [/Схема A/, 'Z+ → Z: перший магніт пропускає лише «+», другий знову вимірює Z.'],
  [/Схема B/, 'Z+ → X+ → Z: між два вимірювання Z вставляємо вимірювання X.'],
  [/^Магніт \d/, 'Увімкни/вимкни магніт. Повзунок = вісь вимірювання (0° = z, 90° = x), фільтр = який пучок проходить.'],
  [/× i/, 'Помнож амплітуду на i = поверни стрілку на 90° проти годинникової стрілки.'],
  [/Знову/, 'Почати головоломку спочатку.'],
  [/Виміряти 1×/, 'Одне вимірювання в базисі Z: дає один біт, і стан «колапсує» в |0⟩ або |1⟩.'],
  [/Виміряти 100 копій/, '100 однаково приготованих копій, кожна виміряна один раз, — так знаходять імовірності.'],
  [/Приготувати/, 'Приготувати новий стан (нову копію кубіта).'],
  [/Надіслати 1(?!\d)/, 'Надіслати один кубіт повільно — стеж, як на кожній станції змінюються стрілка Блоха й матриця ρ.'],
  [/Надіслати 100/, 'Надіслати 100 кубітів одразу й подивитися статистику детектора.'],
  [/Очистити/, 'Обнуляє лічильники / вираз.'],
  [/Перевірити/, 'Перевір, чи складений вираз відповідає завданню.'],
  [/Імпульс із/, 'Скидає спін у |0⟩ і запускає РЧ-імпульс з обраною площею (= кутом повороту).'],
  [/Reset/, 'Повертає стан на початок.'],
  [/CNOT/, 'Керований НЕ: якщо A в |1⟩, перевертає B. Після H на A створює сплутаний стан Белла.'],
  [/H на [AB]/, 'Адамар на одному кубіті.'], [/X на [AB]/, 'Переворот біта одного кубіта.'],
  [/Виміряти 200/, 'Вимірює 200 сплутаних пар в обраних базисах.'],
  [/Зіграти \d+/, 'Грає раунди гри CHSH з твоїми кутами та сплутаною парою.'],
  [/Класично \(/, 'Найкраща класична стратегія: завжди відповідати 0 → 75 %.'],
  [/Підказка/, 'Показує оптимальні кути.'],
  [/Лабораторна система/, 'Ти дивишся з лабораторії: спін прецесує навколо B₀.'], [/Обертова система/, 'Ти обертаєшся разом зі спіном — прецесія зникає.'],
  [/Острів/, 'Назад на Острів Гільберта (розпочатий рівень почнеться знову).'],
  [/Мапа/, 'Мапа острова з порталами (M).'], [/Кодекс/, 'Відкриті символи, особистості й поняття (C).'], [/Щоденник/, 'Усі діалоги та пояснення — прочитати або відтворити знову (L).'],
  [/Амплітуда/, 'Твоя провідниця Амплітуда — комплексне число, що водить тебе островом.'],
  [/^ρ|^\|ρ/, 'Елемент матриці густини: ρ₀₀, ρ₁₁ = імовірності (заселеності), |ρ₀₁| = когерентність (пам’ять фази).'],
  [/^\d: \d+/, 'Кількість результатів 0 або 1 на детекторі.'],
  [/приготування/, 'Кубіт завжди стартує в стані |0⟩.'],
  [/вимірювання Z/, 'Вимірювання в базисі Z із ЗАБУТИМ результатом — руйнує когерентність, лишає суміш.'],
  [/довкілля/, 'Декогеренція: довкілля частково «вимірює» фазу; когерентності зменшуються в (1 − p) разів.'],
  [/^вісь /, 'Вісь обертання гейта, що саме виконується.'],
];

const GLOSS_EN = [
  ['amplitude', 'Amplitude: a complex number attached to an outcome; the probability is its |…|².'],
  ['superposition', 'Superposition: a linear combination of states. Not “we don’t know which one it is in”, nor parallel computing.'],
  ['decoheren', 'Decoherence: the environment destroys phase relations (coherences); the arrow shrinks into the ball.'],
  ['coheren', 'Coherence: a fixed phase relation between the components of a state — it enables interference.'],
  ['interfer', 'Interference: adding amplitudes before squaring; reinforcement or cancellation depending on the phase.'],
  ['entangle', 'Entanglement: the state of the whole cannot be written as a product of states of the parts.'],
  ['relative phase', 'Relative phase: the phase difference between α and β; observable via a measurement in another basis.'],
  ['global phase', 'Global phase: a common factor of the whole state; unobservable.'],
  ['Bloch sphere', 'Bloch sphere: a picture of a qubit state; surface = pure, interior = mixed states.'],
  ['density matri', 'Density matrix ρ: describes states including mixtures; diagonal = populations, off-diagonal = coherences.'],
  ['Born rule', 'Born rule: P = |amplitude|².'],
  ['collaps', 'Collapse: the transition from a quantum possibility to a classical fact during measurement (readout).'],
  ['Hamiltonian', 'Hamiltonian Ĥ: the energy operator that governs time evolution.'],
  ['unitar', 'Unitary operation: reversible, preserves the norm; a rotation on the Bloch sphere.'],
  ['(?:basis|bases)', 'Basis: a set of orthogonal states = the “question” a measurement asks (e.g. Z: |0⟩ or |1⟩?).'],
  ['operator', 'Operator: a “machine” that transforms states; observables are Hermitian operators.'],
  ['expectation value', 'Expectation value ⟨A⟩: the average of many measurements, not the result of one.'],
  ['precess', 'Precession: evolution of the relative phase in the field B₀; P(0), P(1) don’t change.'],
  ['resonan', 'Resonance: the driving frequency matches the natural frequency of the system.'],
  ['complementarit', 'Complementarity (Bohr): wave and particle descriptions complement each other depending on the experiment; not relativism.'],
  ['mixture', 'Mixture: statistical (classical) ignorance; it has no coherences and does not interfere.'],
  ['mixed', 'Mixed state: |r| < 1, inside the Bloch sphere.'],
  ['orthogonal', 'Orthogonal states: inner product 0, perfectly distinguishable by measurement.'],
  ['spin', 'Spin: the quantum form of intrinsic angular momentum — not a spinning ball.'],
  ['qubit', 'Qubit: a quantum system with a two-dimensional complex state space.'],
  ['ket', 'Ket |ψ⟩: notation for a state (column vector).'],
  ['ensemble', 'Ensemble: a large collection of identically prepared systems; NMR measures its average.'],
  ['non-?local', 'Non-locality: influence between distant places without mediation through space.'],
  ['hidden variable', 'Hidden variables: hypothetical values fixed before measurement (Bohm). Bell ruled out local ones.'],
  ['gate', 'Gate: an elementary quantum operation (a unitary rotation).'],
];
const GLOSS_UK = [
  ['амплітуд', 'Амплітуда: комплексне число, приписане результатові; імовірність — її |…|².'],
  ['суперпозиц', 'Суперпозиція: лінійна комбінація станів. Не «ми не знаємо, в якому вона стані» і не паралельні обчислення.'],
  ['декогеренц', 'Декогеренція: довкілля руйнує фазові співвідношення (когерентності); стрілка стискається всередину кулі.'],
  ['когерентн', 'Когерентність: стале фазове співвідношення між складовими стану — уможливлює інтерференцію.'],
  ['інтерфер', 'Інтерференція: додавання амплітуд перед піднесенням до квадрата; підсилення або гасіння залежно від фази.'],
  ['сплутан', 'Сплутаність: стан цілого не можна записати як добуток станів частин.'],
  ['відносн\\p{L}* фаз', 'Відносна фаза: різниця фаз між α і β; спостережувана через вимірювання в іншому базисі.'],
  ['глобальн\\p{L}* фаз', 'Глобальна фаза: спільний множник усього стану; неспостережувана.'],
  ['сфер\\p{L}* Блоха', 'Сфера Блоха: зображення стану кубіта; поверхня = чисті, нутро = змішані стани.'],
  ['матриц\\p{L}* густини', 'Матриця густини ρ: описує стани, включно із сумішами; діагональ = заселеності, позадіагональ = когерентності.'],
  ['правил\\p{L}* Борна', 'Правило Борна: P = |амплітуда|².'],
  ['колапс', 'Колапс: перехід від квантової можливості до класичного факту під час вимірювання (зчитування).'],
  ['гамільтоніан', 'Гамільтоніан Ĥ: оператор енергії, що керує часовою еволюцією.'],
  ['унітарн', 'Унітарна операція: оборотна, зберігає норму; поворот на сфері Блоха.'],
  ['базис', 'Базис: набір ортогональних станів = «питання», яке ставить вимірювання (напр. Z: |0⟩ чи |1⟩?).'],
  ['оператор', 'Оператор: «машина», що перетворює стани; спостережувані — ермітові оператори.'],
  ['середн\\p{L}* значенн', 'Середнє значення ⟨A⟩: середнє багатьох вимірювань, а не результат одного.'],
  ['прецес', 'Прецесія: еволюція відносної фази в полі B₀; P(0), P(1) не змінюються.'],
  ['резонанс', 'Резонанс: частота збудження збігається з власною частотою системи.'],
  ['доповнювальн', 'Доповнювальність (Бор): хвильовий і корпускулярний описи доповнюють один одного залежно від експерименту; це не релятивізм.'],
  ['суміш(?!\\p{L})', 'Суміш: статистичне (класичне) незнання; не має когерентностей і не інтерферує.'],
  ['змішан', 'Змішаний стан: |r| < 1, усередині сфери Блоха.'],
  ['ортогональн', 'Ортогональні стани: скалярний добуток 0, вимірюванням цілком розрізненні.'],
  ['спін', 'Спін: квантова форма власного моменту імпульсу — не кулька, що обертається.'],
  ['кубіт', 'Кубіт: квантова система з двовимірним комплексним простором станів.'],
  ['кет', 'Кет |ψ⟩: запис стану (вектор-стовпець).'],
  ['ансамбл', 'Ансамбль: велика сукупність однаково приготованих систем; ЯМР вимірює її середнє.'],
  ['нелокальн', 'Нелокальність: вплив між віддаленими місцями без посередництва через простір.'],
  ['прихован\\p{L}* змінн', 'Приховані змінні: гіпотетичні значення, визначені до вимірювання (Бом). Локальні виключив Белл.'],
  ['гейт', 'Гейт: елементарна квантова операція (унітарний поворот).'],
];

const TIPS = tr(TIPS_SK, TIPS_EN, TIPS_UK);
const TIP_PATTERNS = tr(TIP_PATTERNS_SK, TIP_PATTERNS_EN, TIP_PATTERNS_UK);
const GLOSS = tr(GLOSS_SK, GLOSS_EN, GLOSS_UK);

const GLOSS_RE = GLOSS.map(([stem, tip]) => [new RegExp(`(?<![\\p{L}\u0002])(${stem}\\p{L}*)`, 'iu'), tip]);

function tipFor(html) {
  const t = String(html).replace(/<br\s*\/?>/g, ' ').replace(/<[^>]+>/g, '').replace(/^[^\p{L}\p{N}|⟨(\[+−×⊗Â⌫ψαρ]+/u, '').trim();
  if (Settings.layman && LAYMAN_TIPS[t]) return LAYMAN_TIPS[t];
  if (TIPS[t]) return TIPS[t];
  const raw = String(html).replace(/<[^>]+>/g, '').trim();
  if (TIPS[raw]) return TIPS[raw];
  for (const [re, tip] of TIP_PATTERNS) if (re.test(t)) return tip;
  return null;
}

// do HTML textu dialógu pridá podčiarknuté pojmy s vysvetlivkou (prvý výskyt každého pojmu)
// inline: v laickej obťažnosti aj krátky preklad žargónu v zátvorke (dialógy a kvízy, nie HUD)
function annotate(html, inline = false) {
  if (Settings.layman) return annotateLayman(html, inline);
  const used = new Set(), tips = [];
  return String(html).split(/(<[^>]+>)/).map((seg) => {
    if (seg.startsWith('<')) return seg;
    for (const [re, tip] of GLOSS_RE) {
      if (used.has(re)) continue;
      const m = seg.match(re);
      if (!m) continue;
      used.add(re); tips.push(tip);
      seg = seg.slice(0, m.index) + `\u0001${tips.length - 1}\u0002${m[1]}\u0003` + seg.slice(m.index + m[1].length);
    }
    return seg.replace(/\u0001(\d+)\u0002([^\u0003]*)\u0003/g, (_, i, w) => `<span class="term" data-tip="${tips[+i].replace(/"/g, '&quot;')}">${w}</span>`);
  }).join('');
}
